always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
short_to_long_function_def = true
always_use_return = false
whitespace_in_kwargs = true
format_docstrings = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
format_markdown = true